// lib-gateway/src/main/webapp/app/entities/libproject/book/update/book-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IBook, Book } from '../book.model';
import { BookService } from '../service/book.service';
import { ICategory } from 'app/entities/libproject/category/category.model';
import { CategoryService } from 'app/entities/libproject/category/service/category.service';

@Component({
  selector: 'jhi-book-update',
  templateUrl: './book-update.component.html',
})
export class BookUpdateComponent implements OnInit {
  isSaving = false;

  categoriesSharedCollection: ICategory[] = [];

  editForm = this.fb.group({
    id: [],
    title: [null, [Validators.required]],
    author: [null, [Validators.required]],
    fine_amount: [null, [Validators.required]],
    publisher: [null, [Validators.required]],
    quantity: [null, [Validators.required]],
    category: [],
  });

  constructor(
    protected bookService: BookService,
    protected categoryService: CategoryService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ book }) => {
      this.updateForm(book);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const book = this.createFromForm();
    if (book.id !== undefined) {
      this.subscribeToSaveResponse(this.bookService.update(book));
    } else {
      this.subscribeToSaveResponse(this.bookService.create(book));
    }
  }

  trackCategoryById(index: number, item: ICategory): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IBook>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(book: IBook): void {
    this.editForm.patchValue({
      id: book.id,
      title: book.title,
      author: book.author,
      fine_amount: book.fine_amount,
      publisher: book.publisher,
      quantity: book.quantity,
      category: book.category,
    });

    this.categoriesSharedCollection = this.categoryService.addCategoryToCollectionIfMissing(this.categoriesSharedCollection, book.category);
  }

  protected loadRelationshipsOptions(): void {
    this.categoryService
      .query()
      .pipe(map((res: HttpResponse<ICategory[]>) => res.body ?? []))
      .pipe(
        map((categories: ICategory[]) =>
          this.categoryService.addCategoryToCollectionIfMissing(categories, this.editForm.get('category')!.value)
        )
      )
      .subscribe((categories: ICategory[]) => (this.categoriesSharedCollection = categories));
  }

  protected createFromForm(): IBook {
    return {
      ...new Book(),
      id: this.editForm.get(['id'])!.value,
      title: this.editForm.get(['title'])!.value,
      author: this.editForm.get(['author'])!.value,
      fine_amount: this.editForm.get(['fine_amount'])!.value,
      publisher: this.editForm.get(['publisher'])!.value,
      quantity: this.editForm.get(['quantity'])!.value,
      category: this.editForm.get(['category'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-book-heading" data-cy="BookCreateUpdateHeading">Create or edit a Book</h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_title">Title</label>
          <input type="text" class="form-control" name="title" id="field_title" data-cy="title" formControlName="title" />
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required"> This field is required. </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_author">Author</label>
          <input type="text" class="form-control" name="author" id="field_author" data-cy="author" formControlName="author" />
          <div *ngIf="editForm.get('author')!.invalid && (editForm.get('author')!.dirty || editForm.get('author')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('author')?.errors?.required"> This field is required. </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_fine_amount">Fine Amount</label>
          <input
            type="number"
            class="form-control"
            name="fine_amount"
            id="field_fine_amount"
            data-cy="fine_amount"
            formControlName="fine_amount"
          />
          <div *ngIf="editForm.get('fine_amount')!.invalid && (editForm.get('fine_amount')!.dirty || editForm.get('fine_amount')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('fine_amount')?.errors?.required"> This field is required. </small>
            <small class="form-text text-danger" [hidden]="!editForm.get('fine_amount')?.errors?.number">
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_publisher">Publisher</label>
          <input type="text" class="form-control" name="publisher" id="field_publisher" data-cy="publisher" formControlName="publisher" />
          <div *ngIf="editForm.get('publisher')!.invalid && (editForm.get('publisher')!.dirty || editForm.get('publisher')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('publisher')?.errors?.required"> This field is required. </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_quantity">Quantity</label>
          <input type="number" class="form-control" name="quantity" id="field_quantity" data-cy="quantity" formControlName="quantity" />
          <div *ngIf="editForm.get('quantity')!.invalid && (editForm.get('quantity')!.dirty || editForm.get('quantity')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('quantity')?.errors?.required"> This field is required. </small>
            <small class="form-text text-danger" [hidden]="!editForm.get('quantity')?.errors?.number">
              This field should be a number.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_category">Category</label>
          <select class="form-control" id="field_category" data-cy="category" name="category" formControlName="category">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="categoryOption.id === editForm.get('category')!.value?.id ? editForm.get('category')!.value : categoryOption"
              *ngFor="let categoryOption of categoriesSharedCollection; trackBy: trackCategoryById"
            >
              {{ categoryOption.name }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// lib-gateway/src/main/webapp/app/entities/libproject/book/book-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2 id="libgatewayApp.libprojectBook.home.createOrEditLabel" data-cy="BookCreateUpdateHeading">Create or edit a Book</h2>
        <div>
          <div class="form-group" v-if="book.id">
            <label for="id">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="book.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="book-title">Title</label>
            <input
              type="text"
              class="form-control"
              name="title"
              id="book-title"
              data-cy="title"
              :class="{ valid: !$v.book.title.$invalid, invalid: $v.book.title.$invalid }"
              v-model="$v.book.title.$model"
              required
            />
            <div v-if="$v.book.title.$anyDirty && $v.book.title.$invalid">
              <small class="form-text text-danger" v-if="!$v.book.title.required"> This field is required. </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="book-author">Author</label>
            <input
              type="text"
              class="form-control"
              name="author"
              id="book-author"
              data-cy="author"
              :class="{ valid: !$v.book.author.$invalid, invalid: $v.book.author.$invalid }"
              v-model="$v.book.author.$model"
              required
            />
            <div v-if="$v.book.author.$anyDirty && $v.book.author.$invalid">
              <small class="form-text text-danger" v-if="!$v.book.author.required"> This field is required. </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="book-fine_amount">Fine Amount</label>
            <input
              type="number"
              class="form-control"
              name="fine_amount"
              id="book-fine_amount"
              data-cy="fine_amount"
              :class="{ valid: !$v.book.fine_amount.$invalid, invalid: $v.book.fine_amount.$invalid }"
              v-model.number="$v.book.fine_amount.$model"
              required
            />
            <div v-if="$v.book.fine_amount.$anyDirty && $v.book.fine_amount.$invalid">
              <small class="form-text text-danger" v-if="!$v.book.fine_amount.required"> This field is required. </small>
              <small class="form-text text-danger" v-if="!$v.book.fine_amount.numeric"> This field should be a number. </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="book-publisher">Publisher</label>
            <input
              type="text"
              class="form-control"
              name="publisher"
              id="book-publisher"
              data-cy="publisher"
              :class="{ valid: !$v.book.publisher.$invalid, invalid: $v.book.publisher.$invalid }"
              v-model="$v.book.publisher.$model"
              required
            />
            <div v-if="$v.book.publisher.$anyDirty && $v.book.publisher.$invalid">
              <small class="form-text text-danger" v-if="!$v.book.publisher.required"> This field is required. </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="book-quantity">Quantity</label>
            <input
              type="number"
              class="form-control"
              name="quantity"
              id="book-quantity"
              data-cy="quantity"
              :class="{ valid: !$v.book.quantity.$invalid, invalid: $v.book.quantity.$invalid }"
              v-model.number="$v.book.quantity.$model"
              required
            />
            <div v-if="$v.book.quantity.$anyDirty && $v.book.quantity.$invalid">
              <small class="form-text text-danger" v-if="!$v.book.quantity.required"> This field is required. </small>
              <small class="form-text text-danger" v-if="!$v.book.quantity.numeric"> This field should be a number. </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="book-category">Category</label>
            <select class="form-control" id="book-category" data-cy="category" name="category" v-model="book.category">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="book.category && categoryOption.id === book.category.id ? book.category : categoryOption"
                v-for="categoryOption in categories"
                :key="categoryOption.id"
              >
                {{ categoryOption.name }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span>Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.book.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span>Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./book-update.component.ts"></script>
