// lib-gateway/src/main/webapp/app/entities/libproject/borrowing/borrowing-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2 id="libgatewayApp.libprojectBorrowing.home.createOrEditLabel" data-cy="BorrowingCreateUpdateHeading">
          Create or edit a Borrowing
        </h2>
        <div>
          <div class="form-group" v-if="borrowing.id">
            <label for="id">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="borrowing.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="borrowing-date_borrowed">Date Borrowed</label>
            <b-input-group class="mb-3">
              <b-input-group-prepend>
                <b-form-datepicker
                  aria-controls="borrowing-date_borrowed"
                  v-model="$v.borrowing.date_borrowed.$model"
                  name="date_borrowed"
                  class="form-control"
                  :locale="currentLanguage"
                  button-only
                  today-button
                  reset-button
                  close-button
                >
                </b-form-datepicker>
              </b-input-group-prepend>
              <b-form-input
                id="borrowing-date_borrowed"
                data-cy="date_borrowed"
                type="text"
                class="form-control"
                name="date_borrowed"
                :class="{ valid: !$v.borrowing.date_borrowed.$invalid, invalid: $v.borrowing.date_borrowed.$invalid }"
                v-model="$v.borrowing.date_borrowed.$model"
              />
            </b-input-group>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="borrowing-due_date">Due Date</label>
            <b-input-group class="mb-3">
              <b-input-group-prepend>
                <b-form-datepicker
                  aria-controls="borrowing-due_date"
                  v-model="$v.borrowing.due_date.$model"
                  name="due_date"
                  class="form-control"
                  :locale="currentLanguage"
                  button-only
                  today-button
                  reset-button
                  close-button
                >
                </b-form-datepicker>
              </b-input-group-prepend>
              <b-form-input
                id="borrowing-due_date"
                data-cy="due_date"
                type="text"
                class="form-control"
                name="due_date"
                :class="{ valid: !$v.borrowing.due_date.$invalid, invalid: $v.borrowing.due_date.$invalid }"
                v-model="$v.borrowing.due_date.$model"
              />
            </b-input-group>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="borrowing-return_date">Return Date</label>
            <b-input-group class="mb-3">
              <b-input-group-prepend>
                <b-form-datepicker
                  aria-controls="borrowing-return_date"
                  v-model="$v.borrowing.return_date.$model"
                  name="return_date"
                  class="form-control"
                  :locale="currentLanguage"
                  button-only
                  today-button
                  reset-button
                  close-button
                >
                </b-form-datepicker>
              </b-input-group-prepend>
              <b-form-input
                id="borrowing-return_date"
                data-cy="return_date"
                type="text"
                class="form-control"
                name="return_date"
                :class="{ valid: !$v.borrowing.return_date.$invalid, invalid: $v.borrowing.return_date.$invalid }"
                v-model="$v.borrowing.return_date.$model"
              />
            </b-input-group>
          </div>
          <div class="form-group">
            <label class="form-control-label" for="borrowing-user_id">User Id</label>
            <input
              type="number"
              class="form-control"
              name="user_id"
              id="borrowing-user_id"
              data-cy="user_id"
              :class="{ valid: !$v.borrowing.user_id.$invalid, invalid: $v.borrowing.user_id.$invalid }"
              v-model.number="$v.borrowing.user_id.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" for="borrowing-book">Book</label>
            <select class="form-control" id="borrowing-book" data-cy="book" name="book" v-model="borrowing.book">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="borrowing.book && bookOption.id === borrowing.book.id ? borrowing.book : bookOption"
                v-for="bookOption in books"
                :key="bookOption.id"
              >
                {{ bookOption.title }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span>Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.borrowing.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span>Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./borrowing-update.component.ts"></script>

// lib-gateway/src/main/webapp/app/entities/libproject/borrowing/update/borrowing-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IBorrowing, Borrowing } from '../borrowing.model';
import { BorrowingService } from '../service/borrowing.service';
import { IBook } from 'app/entities/libproject/book/book.model';
import { BookService } from 'app/entities/libproject/book/service/book.service';
import { IUser } from 'app/entities/user/user.model';
import { UserService } from 'app/entities/user/user.service';

@Component({
  selector: 'jhi-borrowing-update',
  templateUrl: './borrowing-update.component.html',
})
export class BorrowingUpdateComponent implements OnInit {
  isSaving = false;

  booksCollection: IBook[] = [];
  usersSharedCollection: IUser[] = [];

  editForm = this.fb.group({
    id: [],
    date_borrowed: [],
    due_date: [],
    return_date: [],
    book: [],
    user: [],
  });

  constructor(
    protected borrowingService: BorrowingService,
    protected bookService: BookService,
    protected userService: UserService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ borrowing }) => {
      this.updateForm(borrowing);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const borrowing = this.createFromForm();
    if (borrowing.id !== undefined) {
      this.subscribeToSaveResponse(this.borrowingService.update(borrowing));
    } else {
      this.subscribeToSaveResponse(this.borrowingService.create(borrowing));
    }
  }

  trackBookById(index: number, item: IBook): number {
    return item.id!;
  }

  trackUserById(index: number, item: IUser): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IBorrowing>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(borrowing: IBorrowing): void {
    this.editForm.patchValue({
      id: borrowing.id,
      date_borrowed: borrowing.date_borrowed,
      due_date: borrowing.due_date,
      return_date: borrowing.return_date,
      book: borrowing.book,
      user: borrowing.user,
    });

    this.booksCollection = this.bookService.addBookToCollectionIfMissing(this.booksCollection, borrowing.book);
    this.usersSharedCollection = this.userService.addUserToCollectionIfMissing(this.usersSharedCollection, borrowing.user);
  }

  protected loadRelationshipsOptions(): void {
    this.bookService
      .query({ filter: 'id-is-null' })
      .pipe(map((res: HttpResponse<IBook[]>) => res.body ?? []))
      .pipe(map((books: IBook[]) => this.bookService.addBookToCollectionIfMissing(books, this.editForm.get('book')!.value)))
      .subscribe((books: IBook[]) => (this.booksCollection = books));

    this.userService
      .query()
      .pipe(map((res: HttpResponse<IUser[]>) => res.body ?? []))
      .pipe(map((users: IUser[]) => this.userService.addUserToCollectionIfMissing(users, this.editForm.get('user')!.value)))
      .subscribe((users: IUser[]) => (this.usersSharedCollection = users));
  }

  protected createFromForm(): IBorrowing {
    return {
      ...new Borrowing(),
      id: this.editForm.get(['id'])!.value,
      date_borrowed: this.editForm.get(['date_borrowed'])!.value,
      due_date: this.editForm.get(['due_date'])!.value,
      return_date: this.editForm.get(['return_date'])!.value,
      book: this.editForm.get(['book'])!.value,
      user: this.editForm.get(['user'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-borrowing-heading" data-cy="BorrowingCreateUpdateHeading">Create or edit a Borrowing</h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_date_borrowed">Date Borrowed</label>
          <div class="input-group">
            <input
              id="field_date_borrowed"
              data-cy="date_borrowed"
              type="text"
              class="form-control"
              name="date_borrowed"
              ngbDatepicker
              #date_borrowedDp="ngbDatepicker"
              formControlName="date_borrowed"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="date_borrowedDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_due_date">Due Date</label>
          <div class="input-group">
            <input
              id="field_due_date"
              data-cy="due_date"
              type="text"
              class="form-control"
              name="due_date"
              ngbDatepicker
              #due_dateDp="ngbDatepicker"
              formControlName="due_date"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="due_dateDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_return_date">Return Date</label>
          <div class="input-group">
            <input
              id="field_return_date"
              data-cy="return_date"
              type="text"
              class="form-control"
              name="return_date"
              ngbDatepicker
              #return_dateDp="ngbDatepicker"
              formControlName="return_date"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="return_dateDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_book">Book</label>
          <select class="form-control" id="field_book" data-cy="book" name="book" formControlName="book">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="bookOption.id === editForm.get('book')!.value?.id ? editForm.get('book')!.value : bookOption"
              *ngFor="let bookOption of booksCollection; trackBy: trackBookById"
            >
              {{ bookOption.title }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_user">User</label>
          <select class="form-control" id="field_user" data-cy="user" name="user" formControlName="user">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="userOption.id === editForm.get('user')!.value?.id ? editForm.get('user')!.value : userOption"
              *ngFor="let userOption of usersSharedCollection; trackBy: trackUserById"
            >
              {{ userOption.login }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
