// lib-gateway/src/main/webapp/app/entities/libproject/borrowing/list/borrowing.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { combineLatest } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IBorrowing } from '../borrowing.model';

import { ASC, DESC, ITEMS_PER_PAGE, SORT } from 'app/config/pagination.constants';
import { BorrowingService } from '../service/borrowing.service';
import { BorrowingDeleteDialogComponent } from '../delete/borrowing-delete-dialog.component';

@Component({
  selector: 'jhi-borrowing',
  templateUrl: './borrowing.component.html',
})
export class BorrowingComponent implements OnInit {
  borrowings?: IBorrowing[];
  isLoading = false;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page?: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected borrowingService: BorrowingService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number, dontNavigate?: boolean): void {
    this.isLoading = true;
    const pageToLoad: number = page ?? this.page ?? 1;

    this.borrowingService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<IBorrowing[]>) => {
          this.isLoading = false;
          this.onSuccess(res.body, res.headers, pageToLoad, !dontNavigate);
        },
        () => {
          this.isLoading = false;
          this.onError();
        }
      );
  }

  ngOnInit(): void {
    this.handleNavigation();
  }

  trackId(index: number, item: IBorrowing): number {
    return item.id!;
  }

  delete(borrowing: IBorrowing): void {
    const modalRef = this.modalService.open(BorrowingDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.borrowing = borrowing;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadPage();
      }
    });
  }

  protected sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? ASC : DESC)];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected handleNavigation(): void {
    combineLatest([this.activatedRoute.data, this.activatedRoute.queryParamMap]).subscribe(([data, params]) => {
      const page = params.get('page');
      const pageNumber = +(page ?? 1);
      const sort = (params.get(SORT) ?? data['defaultSort']).split(',');
      const predicate = sort[0];
      const ascending = sort[1] === ASC;
      if (pageNumber !== this.page || predicate !== this.predicate || ascending !== this.ascending) {
        this.predicate = predicate;
        this.ascending = ascending;
        this.loadPage(pageNumber, true);
      }
    });
  }

  protected onSuccess(data: IBorrowing[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    if (navigate) {
      this.router.navigate(['/borrowing'], {
        queryParams: {
          page: this.page,
          size: this.itemsPerPage,
          sort: this.predicate + ',' + (this.ascending ? ASC : DESC),
        },
      });
    }
    this.borrowings = data ?? [];
    this.ngbPaginationPage = this.page;
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page ?? 1;
  }
}

<div>
  <h2 id="page-heading" data-cy="BorrowingHeading">
    <span>Borrowings</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadPage()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span>Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-borrowing"
        [routerLink]="['/borrowing/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span> Create a new Borrowing </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="borrowings?.length === 0">
    <span>No borrowings found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="borrowings && borrowings.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="loadPage()">
          <th scope="col" jhiSortBy="id"><span>ID</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="date_borrowed"><span>Date Borrowed</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="due_date"><span>Due Date</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="return_date"><span>Return Date</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="book.title"><span>Book</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="user.login"><span>User</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let borrowing of borrowings; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/borrowing', borrowing.id, 'view']">{{ borrowing.id }}</a>
          </td>
          <td>{{ borrowing.date_borrowed | formatMediumDate }}</td>
          <td>{{ borrowing.due_date | formatMediumDate }}</td>
          <td>{{ borrowing.return_date | formatMediumDate }}</td>
          <td>
            <div *ngIf="borrowing.book">
              <a [routerLink]="['/book', borrowing.book?.id, 'view']">{{ borrowing.book?.title }}</a>
            </div>
          </td>
          <td>
            {{ borrowing.user?.login }}
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/borrowing', borrowing.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/borrowing', borrowing.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline">Edit</span>
              </button>

              <button type="submit" (click)="delete(borrowing)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div *ngIf="borrowings && borrowings.length > 0">
    <div class="row justify-content-center">
      <jhi-item-count [params]="{ page: page, totalItems: totalItems, itemsPerPage: itemsPerPage }"></jhi-item-count>
    </div>

    <div class="row justify-content-center">
      <ngb-pagination
        [collectionSize]="totalItems"
        [(page)]="ngbPaginationPage"
        [pageSize]="itemsPerPage"
        [maxSize]="5"
        [rotate]="true"
        [boundaryLinks]="true"
        (pageChange)="loadPage($event)"
      ></ngb-pagination>
    </div>
  </div>
</div>

// lib-gateway/src/main/webapp/app/entities/libproject/borrowing/borrowing.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="BorrowingHeading">
      <span id="borrowing-heading">Borrowings</span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" v-on:click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon> <span>Refresh List</span>
        </button>
        <router-link :to="{ name: 'BorrowingCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-borrowing"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span> Create a new Borrowing </span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && borrowings && borrowings.length === 0">
      <span>No borrowings found</span>
    </div>
    <div class="table-responsive" v-if="borrowings && borrowings.length > 0">
      <table class="table table-striped" aria-describedby="borrowings">
        <thead>
          <tr>
            <th scope="row" v-on:click="changeOrder('id')">
              <span>ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('date_borrowed')">
              <span>Date Borrowed</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'date_borrowed'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('due_date')">
              <span>Due Date</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'due_date'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('return_date')">
              <span>Return Date</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'return_date'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('user_id')">
              <span>User Id</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'user_id'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('book.title')">
              <span>Book</span>
              <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'book.title'"></jhi-sort-indicator>
            </th>
            <th scope="row" v-on:click="changeOrder('fine')">
                          <span>Fine Accrued</span>
                          <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'user_id'"></jhi-sort-indicator>
                        </th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="borrowing in borrowings" :key="borrowing.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'BorrowingView', params: { borrowingId: borrowing.id } }">{{ borrowing.id }}</router-link>
            </td>
            <td>{{ borrowing.date_borrowed }}</td>
            <td>{{ borrowing.due_date }}</td>
            <td>{{ borrowing.return_date }}</td>
            <td>{{ borrowing.user_id }}</td>
            <td>
              <div v-if="borrowing.book">
                <router-link :to="{ name: 'BookView', params: { bookId: borrowing.book.id } }">{{ borrowing.book.title }}</router-link>
              </div>
            </td>
            <td>{{ borrowing.fine_accrued}}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'BorrowingView', params: { borrowingId: borrowing.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline">View</span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'BorrowingEdit', params: { borrowingId: borrowing.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline">Edit</span>
                  </button>
                </router-link>
                <b-button
                  v-on:click="prepareRemove(borrowing)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline">Delete</span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <span slot="modal-title"
        ><span id="libgatewayApp.libprojectBorrowing.delete.question" data-cy="borrowingDeleteDialogHeading"
          >Confirm delete operation</span
        ></span
      >
      <div class="modal-body">
        <p id="jhi-delete-borrowing-heading">Are you sure you want to delete this Borrowing?</p>
      </div>
      <div slot="modal-footer">
        <button type="button" class="btn btn-secondary" v-on:click="closeDialog()">Cancel</button>
        <button
          type="button"
          class="btn btn-primary"
          id="jhi-confirm-delete-borrowing"
          data-cy="entityConfirmDeleteButton"
          v-on:click="removeBorrowing()"
        >
          Delete
        </button>
      </div>
    </b-modal>
    <div v-show="borrowings && borrowings.length > 0">
      <div class="row justify-content-center">
        <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
      </div>
      <div class="row justify-content-center">
        <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
      </div>
    </div>
  </div>
</template>

<script lang="ts" src="./borrowing.component.ts"></script>
